using NexusEnroll.Core.Services;

namespace NexusEnroll.Core.Entities;

public class Administrator
{
    public string AdminId { get; }
    public string Name { get; }

    public Administrator(string adminId, string name)
    {
        AdminId = adminId;
        Name = name;
    }

    public void ManageCourse(Course course) =>
        Console.WriteLine($"Admin {Name} managed course: {course.Name}");

    public void ManageAccount(object user) =>
        Console.WriteLine($"Admin {Name} managed account for user: {user}");

    public Report GenerateReport(string type) =>
        new Report(type, $"Mock {type} Report")
        {
            Content = new List<string>
            {
                $"Report generated by Admin {Name}.",
                $"Generated at {DateTime.Now:yyyy-MM-dd HH:mm}."
            }
        };

    public bool OverrideEnrollment(Student student, Course course, EnrollmentService service) =>
        service.ForceEnroll(student, course);
}